services:
    main:
        container_name: main
        build: .
        env_file: .env
        ports:
            - '3000:3000'
            - '9229:9229'
        restart: always
        network_mode: mynet

networks:
  mynet:
    driver: bridge